#include "main.h"

HFONT GetNewFont() {
	HFONT	MyFont = CreateFont (16, 0, FW_DONTCARE, FW_DONTCARE, FW_DONTCARE, FALSE, FALSE, FALSE, ANSI_CHARSET, OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, DEFAULT_QUALITY, FF_DONTCARE, "Arial");
	return	MyFont;
}